"""
ATHENA - Presenter Service
TODO-7 ✓: Pure local report generator — no LLM, no external calls.

Transforms StrategyResult + AnalystResult into:
  - A structured multi-section Markdown report saved to disk
  - A pitch deck outline (8 slides) derived from the report

Report sections:
  1. Executive Overview
  2. Market & Competitors
  3. Market Trends
  4. Customer Segments       ← added LATS pass 5
  5. Strategic Analysis — SWOT
  6. Positioning Options
  7. Go-to-Market Plan
  8. Next Steps

Note: report_url points to /api/v1/reports/{job_id}.md which is served by the
      FastAPI StaticFiles mount configured in main.py (TODO-10 ✓).
"""
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from app.core.config import settings
from app.models.schemas import (
    AnalystResult,
    DeckSlide,
    PresenterResult,
    StrategyResult,
)

logger = logging.getLogger(__name__)


# ── helpers ───────────────────────────────────────────────────────────────────

def _fmt_bullets(items: list[str], indent: str = "") -> str:
    return "\n".join(f"{indent}- {item}" for item in items) if items else f"{indent}- N/A"


def _confidence_badge(level: str) -> str:
    return {"high": "\U0001f7e2 High", "medium": "\U0001f7e1 Medium", "low": "\U0001f534 Low"}.get(level.lower(), level)


# ── Markdown report builder ───────────────────────────────────────────────────────────────

def _build_report_markdown(
    job_id: str,
    strategy: StrategyResult,
    analyst: Optional[AnalystResult],
) -> str:
    now    = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    target = strategy.target
    lines: list[str] = []

    lines += [
        f"# ATHENA Competitive Intelligence Report \u2014 {target}",
        "",
        f"> **Generated by ATHENA** on {now}  ",
        f"> Job ID: `{job_id}`",
        "",
        "---",
        "",
    ]

    # 1. Executive Overview
    lines += ["## 1. Executive Overview", ""]
    if strategy.strategic_summary:
        lines += [strategy.strategic_summary, ""]
    if strategy.positioning_options:
        best = strategy.positioning_options[strategy.recommended_positioning_index]
        lines += [
            f"**Recommended Positioning:** {best.statement}",
            "",
            f"**Target Audience:** {best.target_audience}",
            "",
            f"**Key Differentiator:** {best.key_differentiator}",
            "",
        ]
    lines += ["---", ""]

    # 2. Market & Competitors
    lines += ["## 2. Market & Competitors", ""]
    if analyst and analyst.competitors:
        lines += [
            "| Competitor | Market Position | Confidence | Assumption |",
            "|---|---|---|---|",
        ]
        for c in analyst.competitors:
            pos   = c.market_position or "\u2014"
            badge = _confidence_badge(c.confidence)
            flag  = "\u26a0\ufe0f Yes" if c.is_assumption else "\u2705 No"
            lines.append(f"| {c.name} | {pos} | {badge} | {flag} |")
        lines += [""]
        if analyst.high_confidence_competitors:
            lines += [f"**High-confidence confirmed competitors:** {', '.join(analyst.high_confidence_competitors)}", ""]
    else:
        lines += ["*No competitor data available.*", ""]
    lines += ["---", ""]

    # 3. Market Trends
    lines += ["## 3. Market Trends", ""]
    if analyst and analyst.trends:
        for t in analyst.trends:
            badge      = _confidence_badge(t.impact)
            tf         = f" *(~{t.timeframe})*" if t.timeframe else ""
            assumption = " \u26a0\ufe0f *assumption*" if t.is_assumption else ""
            lines += [f"### {t.title} \u2014 {badge}{assumption}", "", f"{t.description}{tf}", ""]
    else:
        lines += ["*No trend data available.*", ""]
    lines += ["---", ""]

    # 4. Customer Segments
    lines += ["## 4. Customer Segments", ""]
    if analyst and analyst.segments:
        for seg in analyst.segments:
            size = f" *(est. {seg.estimated_size})*" if seg.estimated_size else ""
            lines += [f"### {seg.name}{size}", "", seg.description, ""]
            if seg.pain_points:
                lines += ["**Pain Points:**", "", _fmt_bullets(seg.pain_points), ""]
    else:
        lines += ["*No customer segment data available.*", ""]
    lines += ["---", ""]

    # 5. SWOT
    lines += ["## 5. Strategic Analysis \u2014 SWOT", ""]
    if strategy.swot:
        s = strategy.swot
        for section, items in [
            ("### \U0001f4aa Strengths",       s.strengths),
            ("### \U0001f527 Weaknesses",      s.weaknesses),
            ("### \U0001f680 Opportunities",   s.opportunities),
            ("### \u26a0\ufe0f Threats",         s.threats),
        ]:
            lines += [section, "", _fmt_bullets(items), ""]
    else:
        lines += ["*SWOT data not available.*", ""]
    lines += ["---", ""]

    # 6. Positioning Options
    lines += ["## 6. Positioning Options", ""]
    for i, opt in enumerate(strategy.positioning_options):
        tag = " *(Recommended)*" if i == strategy.recommended_positioning_index else ""
        lines += [
            f"### Option {i + 1}: {opt.name}{tag}",
            "",
            f"**Statement:** {opt.statement}",
            "",
            f"**Target Audience:** {opt.target_audience}",
            "",
            f"**Key Differentiator:** {opt.key_differentiator}",
            "",
            f"**Risk Level:** {_confidence_badge(opt.risk_level)}",
            "",
        ]
        if opt.rationale:
            lines += [f"**Rationale:** {opt.rationale}", ""]
    lines += ["---", ""]

    # 7. GTM Plan
    lines += ["## 7. Go-to-Market Plan", ""]
    gtm = strategy.gtm_plan
    if gtm:
        if gtm.icp:
            icp = gtm.icp
            lines += ["### Ideal Customer Profile (ICP)", "", icp.description, ""]
            for label, val in [
                ("Company Size", icp.company_size),
                ("Industry",     icp.industry),
                ("Geography",    icp.geography),
            ]:
                if val:
                    lines.append(f"- **{label}:** {val}")
            lines += [""]
            if icp.pain_points:
                lines += ["**Pain Points:**", "", _fmt_bullets(icp.pain_points), ""]
            if icp.buying_triggers:
                lines += ["**Buying Triggers:**", "", _fmt_bullets(icp.buying_triggers), ""]
        if gtm.channels:
            lines += ["### Channels", "", _fmt_bullets(gtm.channels), ""]
        if gtm.messaging_pillars:
            lines += ["### Messaging Pillars", "", _fmt_bullets(gtm.messaging_pillars), ""]
        if gtm.value_proposition:
            lines += ["### Value Proposition", "", f"> {gtm.value_proposition}", ""]
        if gtm.launch_phases:
            lines += ["### Launch Roadmap", ""]
            for phase in gtm.launch_phases:
                dur = f" \u2014 {phase.duration}" if phase.duration else ""
                lines += [f"#### {phase.name}{dur}", ""]
                if phase.actions:
                    lines += ["**Actions:**", "", _fmt_bullets(phase.actions), ""]
                if phase.success_metrics:
                    lines += ["**Success Metrics:**", "", _fmt_bullets(phase.success_metrics), ""]
        if gtm.competitive_moat:
            lines += ["### Competitive Moat", "", gtm.competitive_moat, ""]
    else:
        lines += ["*GTM plan not available.*", ""]
    lines += ["---", ""]

    # 8. Next Steps
    lines += ["## 8. Next Steps", ""]
    next_steps: list[str] = []
    if gtm and gtm.launch_phases:
        for phase in gtm.launch_phases[:2]:
            next_steps.extend(phase.actions[:3])
    if not next_steps and strategy.swot:
        next_steps = [
            f"Address weakness: {strategy.swot.weaknesses[0]}"       if strategy.swot.weaknesses    else "",
            f"Exploit opportunity: {strategy.swot.opportunities[0]}" if strategy.swot.opportunities else "",
        ]
        next_steps = [ns for ns in next_steps if ns]
    if next_steps:
        for idx, step in enumerate(next_steps[:8], start=1):
            lines.append(f"{idx}. {step}")
        lines += [""]
    else:
        lines += ["1. Define MVP scope and ICP", "2. Run competitive monitoring pilot", ""]

    lines += [
        "---",
        "",
        "*Report generated by **ATHENA** \u2014 Autonomous Multi-Agent Market Intelligence Platform*",
        "",
        f"*Pipeline: Scout \u2192 Analyst \u2192 Strategy \u2192 Presenter | Job ID: `{job_id}` | {now}*",
    ]
    return "\n".join(lines)


# ── Deck outline builder ──────────────────────────────────────────────────────────────────────

def _build_deck_outline(
    strategy: StrategyResult,
    analyst: Optional[AnalystResult],
) -> list[DeckSlide]:
    target = strategy.target
    slides: list[DeckSlide] = []

    # Slide 1: Cover
    tagline = strategy.positioning_options[0].name if strategy.positioning_options else "Competitive Intelligence Report"
    slides.append(DeckSlide(
        slide_number=1,
        title=f"ATHENA \u2014 {target}",
        bullets=[
            "Competitive Intelligence Report",
            f"Target: {target}",
            tagline,
            f"Generated: {datetime.now(timezone.utc).strftime('%B %Y')}",
        ],
        speaker_note="Introduce ATHENA and the target. Mention the multi-agent pipeline.",
    ))

    # Slide 2: Executive Summary
    summary_bullets = [
        s.strip() for s in strategy.strategic_summary.split(".")
        if len(s.strip()) > 10
    ][:4] or ["Strategic analysis complete", "Key findings available across all sections"]
    slides.append(DeckSlide(
        slide_number=2,
        title="Executive Summary",
        bullets=summary_bullets,
        speaker_note="High-level takeaways. Keep it to 3-4 sentences max.",
    ))

    # Slide 3: Market Landscape
    comp_count  = len(analyst.competitors) if analyst else "N/A"
    trend_count = len(analyst.trends)      if analyst else "N/A"
    seg_count   = len(analyst.segments)    if analyst else "N/A"
    top_comps   = ", ".join(c.name for c in analyst.competitors[:4]) if analyst and analyst.competitors else "See full report"
    slides.append(DeckSlide(
        slide_number=3,
        title="Market Landscape",
        bullets=[
            f"{comp_count} competitors identified",
            f"Top: {top_comps}",
            f"{trend_count} market trends tracked",
            f"{seg_count} customer segments analysed",
        ],
        speaker_note="Set the scene \u2014 how crowded is the market?",
    ))

    # Slide 4: Competitive Analysis
    comp_bullets: list[str] = []
    if analyst and analyst.competitors:
        for c in analyst.competitors[:5]:
            badge = "\u2705" if not c.is_assumption else "\u26a0\ufe0f"
            comp_bullets.append(f"{badge} {c.name} \u2014 {c.market_position or c.description[:60]}")
    comp_bullets = comp_bullets or ["No confirmed competitors identified"]
    slides.append(DeckSlide(
        slide_number=4,
        title="Competitive Analysis",
        bullets=comp_bullets,
        speaker_note="Walk through top competitors. \u2705 = confirmed, \u26a0\ufe0f = inferred.",
    ))

    # Slide 5: Market Trends
    trend_bullets: list[str] = []
    if analyst and analyst.trends:
        for t in analyst.trends[:5]:
            icon = {"high": "\U0001f534", "medium": "\U0001f7e1", "low": "\U0001f7e2"}.get(t.impact.lower(), "\u26aa")
            trend_bullets.append(f"{icon} {t.title}")
    trend_bullets = trend_bullets or ["Trend data not available"]
    slides.append(DeckSlide(
        slide_number=5,
        title="Market Trends",
        bullets=trend_bullets,
        speaker_note="Highlight high-impact trends (\U0001f534) first.",
    ))

    # Slide 6: SWOT Analysis
    swot_bullets: list[str] = []
    if strategy.swot:
        s = strategy.swot
        if s.strengths:     swot_bullets.append(f"\U0001f4aa S: {s.strengths[0]}")
        if s.weaknesses:    swot_bullets.append(f"\U0001f527 W: {s.weaknesses[0]}")
        if s.opportunities: swot_bullets.append(f"\U0001f680 O: {s.opportunities[0]}")
        if s.threats:       swot_bullets.append(f"\u26a0\ufe0f T: {s.threats[0]}")
    swot_bullets = swot_bullets or ["SWOT analysis not available"]
    slides.append(DeckSlide(
        slide_number=6,
        title="SWOT Analysis",
        bullets=swot_bullets,
        speaker_note="Use 2\u00d72 SWOT grid visual.",
    ))

    # Slide 7: Recommended Positioning
    pos_bullets: list[str] = []
    if strategy.positioning_options:
        best = strategy.positioning_options[strategy.recommended_positioning_index]
        pos_bullets = [
            f"Name: {best.name}",
            f"Statement: {best.statement}",
            f"Audience: {best.target_audience}",
            f"Differentiator: {best.key_differentiator}",
            f"Risk: {best.risk_level}",
        ]
    else:
        pos_bullets = ["Positioning options not available"]
    slides.append(DeckSlide(
        slide_number=7,
        title="Recommended Positioning",
        bullets=pos_bullets,
        speaker_note="Why this positioning? Tie back to SWOT opportunities and competitor gaps.",
    ))

    # Slide 8: GTM Plan & Next Steps
    gtm_bullets: list[str] = []
    if strategy.gtm_plan:
        gtm = strategy.gtm_plan
        if gtm.value_proposition: gtm_bullets.append(f"Value Prop: {gtm.value_proposition}")
        if gtm.channels:          gtm_bullets.append(f"Channels: {', '.join(gtm.channels[:3])}")
        if gtm.launch_phases:
            gtm_bullets.append(f"Phase 1: {gtm.launch_phases[0].name}")
            if len(gtm.launch_phases) > 1:
                gtm_bullets.append(f"Phase 2: {gtm.launch_phases[1].name}")
        if gtm.competitive_moat:  gtm_bullets.append(f"Moat: {gtm.competitive_moat[:80]}\u2026")
    gtm_bullets = gtm_bullets or ["GTM plan not available"]
    slides.append(DeckSlide(
        slide_number=8,
        title="GTM Plan & Next Steps",
        bullets=gtm_bullets,
        speaker_note="Close with action plan. Emphasise 30/60/90-day milestones.",
    ))

    return slides


# ── File writer ─────────────────────────────────────────────────────────────────────────

def _write_report(job_id: str, markdown: str) -> str:
    reports_dir = Path(settings.REPORTS_DIR).resolve()
    reports_dir.mkdir(parents=True, exist_ok=True)
    report_path = reports_dir / f"{job_id}.md"
    try:
        report_path.write_text(markdown, encoding="utf-8")
        logger.info("[PRESENTER] Report written to: %s  (%d chars)", report_path, len(markdown))
    except OSError as exc:
        logger.error("[PRESENTER] Failed to write report to disk: %s", exc)
        # Non-fatal — in-memory report_markdown is still returned to the caller
    return str(report_path)


# ── Main entry point ────────────────────────────────────────────────────────────────────

async def run_presenter(
    job_id: str,
    strategy_result: StrategyResult,
    analyst_result: Optional[AnalystResult] = None,
) -> PresenterResult:
    """
    TODO-7 ✓: Generates the Markdown report and deck outline, writes report to disk.

    Steps:
      1. Build 8-section Markdown report from strategy + analyst data
      2. Build 8-slide pitch deck outline
      3. Write .md file to REPORTS_DIR/{job_id}.md  (non-fatal on I/O error)
      4. Return PresenterResult

    The generated report is served statically at /api/v1/reports/{job_id}.md
    via the FastAPI StaticFiles mount in main.py.
    """
    logger.info(
        "[PRESENTER] run_presenter started — job='%s', target='%s'",
        job_id, strategy_result.target,
    )

    report_markdown = _build_report_markdown(job_id, strategy_result, analyst_result)
    deck_outline    = _build_deck_outline(strategy_result, analyst_result)
    report_path     = _write_report(job_id, report_markdown)
    report_url      = f"/api/v1/reports/{job_id}.md"

    result = PresenterResult(
        job_id=job_id,
        target=strategy_result.target,
        report_markdown=report_markdown,
        deck_outline=deck_outline,
        report_path=report_path,
        report_url=report_url,
        presented_at=datetime.now(timezone.utc),
    )
    logger.info(
        "[PRESENTER] complete — %d slides, %d chars report",
        len(deck_outline), len(report_markdown),
    )
    return result
