# ATHENA CI Workflow
# Copy this file to .github/workflows/ci.yml to activate GitHub Actions CI.
# Requires the 'workflow' OAuth scope on your GitHub token.
#
# Jobs:
#   backend-tests   - pytest (~167 tests) in stub mode, no credentials needed
#   frontend-checks - TypeScript type-check + ESLint
#   docker-build    - validates both Dockerfiles build correctly

name: CI

on:
  push:
    branches: [main, "feature/**", "bugfix/**", "hotfix/**"]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    name: "Backend pytest (Python 3.11)"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: backend/requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests with coverage
        run: |
          pytest tests/ -v --tb=short \
            --cov=app \
            --cov-report=term-missing \
            --cov-report=xml:coverage.xml
        env:
          STUB_MODE: "true"
          DEPLOY_AI_CLIENT_ID: ""
          DEPLOY_AI_CLIENT_SECRET: ""
          DEPLOY_AI_ORG_ID: ""
          REPORTS_DIR: "/tmp/athena-ci-reports"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-coverage
          path: backend/coverage.xml
          retention-days: 7

  frontend-checks:
    name: "Frontend TypeScript + ESLint (Node 20)"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: TypeScript type check
        run: npx tsc --noEmit
      - name: ESLint
        run: npm run lint
        env:
          NEXT_PUBLIC_API_URL: "http://localhost:8000"

  docker-build:
    name: "Docker build validation"
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-checks]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: false
          tags: athena-backend:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: false
          tags: athena-frontend:ci
          build-args: NEXT_PUBLIC_API_URL=http://localhost:8000
          cache-from: type=gha
          cache-to: type=gha,mode=max
